### PR TITLE
Remove Authorization Code + PKCE Power BI

### PR DESCRIPTION
**Pull request by anton-dahlin**

### CODE REVIEW

**Review by kelseyduffy — CHANGES_REQUESTED** [review]
This should also be removed from the authentication.md page
https://github.com/osisoft/OSI-Samples-ADH/blob/main/docs/AUTHENTICATION.md

**Comment by cfoisy-osisoft** [comment]
FYI re: https://github.com/osisoft/OSI-Samples-ADH/blob/main/docs/AUTHENTICATION.md

The link for "here" in the text for hybrid (https://github.com/osisoft/sample-adh-authentication_hybrid_flow-dotnet) currently returns 404 and should be changed for the correct one present in the table (https://github.com/osisoft/sample-adh-authentication_hybrid-dotnet)

**Comment by anton-dahlin** [comment]
> FYI re: https://github.com/osisoft/OSI-Samples-ADH/blob/main/docs/AUTHENTICATION.md
> 
> The link for "here" in the text for hybrid (https://github.com/osisoft/sample-adh-authentication_hybrid_flow-dotnet) currently returns 404 and should be changed for the correct one present in the table (https://github.com/osisoft/sample-adh-authentication_hybrid-dotnet)

Thank you Christian, this is being corrected in a PR by Collin https://github.com/osisoft/OSI-Samples-ADH/pull/218/files

**Comment by anton-dahlin** [comment]
> This should also be removed from the authentication.md page https://github.com/osisoft/OSI-Samples-ADH/blob/main/docs/AUTHENTICATION.md

I also fixed the Set Up Now

**Review by derekendres — APPROVED** [review]

**Pull request merged**
